# Jekyll Configuration

# General metadata
name: boxes
title: boxes
description: 'Command line ASCII boxes unlimited!'
tagline: 'Command line ASCII boxes unlimited!'

# Deployment
baseurl: ''
url: 'https://boxes.thomasjensen.com'

# Social Media
github: 'ascii-boxes/boxes'
twitter_username: tj_impl

# Plugins from the whitelist at https://github.com/github/pages-gem/blob/master/lib/github-pages/plugins.rb
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Which paths are processed by Jekyll to appear under _site/
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - cmake-build-debug/
  - coverage/
  - doc/
  - flex_bison_2.5.24/
  - js.bat
  - out/
  - pcre2-10.36/
  - src/
  - vs

include:
  - pages/

# Permalinks / blog post URLs
permalink: /:year/:month/:title:output_ext
future: true

# Split the what's new page into multiple pages
paginate: 10
paginate_path: /blog/page:num/

# Analytics
plausible:
    data_domain: 'boxes.thomasjensen.com'

# Minify CSS
sass:
    style: compressed

# Do not create redirects.json file
redirect_from:
    json: false

# boxes custom variables
currentVersion: '2.1.0'
link_license: 'https://raw.githubusercontent.com/ascii-boxes/boxes/v2.1.0/LICENSE'

# Page frontmatter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
