# Jekyll configuration

name: boxes
description: Command line ASCII boxes unlimited!

plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap

# url is currently only used only for the RSS feed in feed.xml
url: https://boxes.thomasjensen.com

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
#baseurl: /boxes
baseurl: ''

github: 'ascii-boxes/boxes'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: 'UA-23698164-5'

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: ''
comments: false

permalink: /:year/:month/:title:output_ext
paginate: 10
future: true

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

exclude: ['README.md', 'LICENSE', 'src/', 'doc/']

currentVersion: 2.0.0

# boxes custom variables
defaults:
  -
    scope:
      path: ""   # everywhere
    values:
      bxemail: '&lt;boxes(at)thomasjensen.com&gt;'
      sitehost: 'boxes.thomasjensen.com'
