name: build

on: [push, pull_request, workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: add-packages
              run: |
                  sudo apt-get update -y
                  sudo apt-get install -y git flex bison libunistring-dev libpcre2-dev diffutils vim-common lcov

            - name: make cov
              run: make cov

            - name: make covtest
              run: make covtest

            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  path-to-lcov: out/lcov-blackbox.info
